### ISSUE TITLE
Incompatibilities with django 1.10

### ISSUE THREAD

**Issue by SalahAdDin** [django-oscar/django-oscar#2072]
Hi guys, now i update `django` to `1.10` version and i have this problem:

```bash
 salahaddin@TulipanROG  ~/Proyectos/demo-oscar/ecommerce   master ● ?  (demo-oscar)  ./manage.py runserver                                                                                               ✓  1685  18:14:32 
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f7ed4947730>
Traceback (most recent call last):
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/core/management/commands/runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/utils/autoreload.py", line 249, in raise_last_exception
    six.reraise(*_exception)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/utils/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/utils/autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/apps/registry.py", line 108, in populate
    app_config.import_models(all_models)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/django/apps/config.py", line 199, in import_models
    self.models_module = import_module(models_module_name)
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 665, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/oscar/apps/address/models.py", line 1, in <module>
    from oscar.apps.address.abstract_models import (
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/oscar/apps/address/abstract_models.py", line 13, in <module>
    from oscar.models.fields import PhoneNumberField, UppercaseCharField
  File "/home/salahaddin/Proyectos/demo-oscar/lib/python3.5/site-packages/oscar/models/fields/__init__.py", line 3, in <module>
    from django.db.models import SubfieldBase
ImportError: cannot import name 'SubfieldBase'

```

[Here ](https://github.com/omab/python-social-auth/issues/755) are a solution for this problem.

I'll report some problems with django 1.10.

Thanks you!

**Comment by mvantellingen** [comment]
Thanks, we are aware of this and it is currently worked on by @pxg

**Comment by prabhatpankaj** [comment]
hi SalahAdDin , 
I am facing same problem , I tried to understand the solution . but couldn't. 

File "/home/ubuntu/workspace/zabrabox/production/local/lib/python2.7/site-packages/oscar/models/fields/__init__.py", line 3, in <module>
    from django.db.models import SubfieldBase
ImportError: cannot import name SubfieldBase

. please suggest me which file cone i need to change .

thanks you soo much in advance .

**Comment by pxg** [comment]
@prabhatpankaj I have a branch in my fork where I'm working on Django 1.10 compatibility https://github.com/pxg/django-oscar/tree/feature/django-110 however not all test are passing so this work should definitely be considered unstable. The `SubfieldBase` issue isn't the only one with upgrading to Django 1.10.

**Comment by SalahAdDin** [comment]
@mvantellingen Where django-oscar going to support `django 1.10` ?

**Comment by saintger** [comment]
Hello,
I wanted to use django-oscar for a prototype website with Django 1.10, so I made some changes to make it work:
https://github.com/pxg/django-oscar/pull/1
I haven't checked the test, I just wanted to have a quick look (so it's a quick&dirty change).
Hope that may help.

**Comment by pxg** [comment]
@saintger thanks for this, will be useful for you to confirm that this works for your prototype. I think the main thing blocking us on this is getting the tests passing.

**Comment by saintger** [comment]
@pxg I just ran the test and I have only 6 failed tests.
However with Django 1.9.10, I have 2 failed tests as well.
I'll try to have a look at these 4 failed tests within 1-2 weeks.

**Comment by pxg** [comment]
Ok great, let me know if you need a hand. I have an Oscar site I want to update to Django 1.10 so keen to get this working.

**Comment by saintger** [comment]
@pxg Perhaps I need indeed you help to start debugging.
I'm trying to check the first failure:

```
./runtests.py tests/functional/checkout/customer_checkout_tests.py::TestUserAddressUpdateView
============================================================================== test session starts ===============================================================================
platform linux2 -- Python 2.7.9, pytest-2.8.5, py-1.4.31, pluggy-0.3.1
django settings: tests.settings (from environment variable)
rootdir: /home/user/workspace/django-oscar, inifile: setup.cfg
plugins: cov-2.2.0, django-2.9.1, xdist-1.13.1
collected 2 items 

tests/functional/checkout/customer_checkout_tests.py
F

==================================================================================== FAILURES ====================================================================================
_________________________________________________________________ TestUserAddressUpdateView.test_requires_login __________________________________________________________________

self = <tests.functional.checkout.customer_checkout_tests.TestUserAddressUpdateView testMethod=test_requires_login>

    def test_requires_login(self):
        response = self.get(
            reverse('checkout:user-address-update',
                    kwargs={'pk': self.user_address.pk}),
>           user=None)

tests/functional/checkout/customer_checkout_tests.py:97: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
src/oscar/test/testcases.py:61: in get
    return self.app.get(url, **kwargs)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django_webtest/__init__.py:111: in get
    url, params, headers, extra_environ, status, expect_errors, **kwargs)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/webtest/app.py:322: in get
    expect_errors=expect_errors)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django_webtest/__init__.py:74: in do_request
    response = super(DjangoTestApp, self).do_request(req, status, expect_errors)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/webtest/app.py:605: in do_request
    res = req.get_response(app, catch_exc_info=True)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/webob/request.py:1295: in send
    application, catch_exc_info=True)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/webob/request.py:1263: in call_application
    app_iter = application(self.environ, start_response)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/webtest/lint.py:198: in lint_app
    iterator = application(environ, start_response_wrapper)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py:63: in __call__
    return self.application(environ, start_response)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django/core/handlers/wsgi.py:170: in __call__
    response = self.get_response(request)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django/core/handlers/base.py:124: in get_response
    response = self._middleware_chain(request)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django/core/handlers/exception.py:41: in inner
    response = response_for_exception(request, exc)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django/core/handlers/exception.py:86: in response_for_exception
    response = handle_uncaught_exception(request, get_resolver(get_urlconf()), sys.exc_info())
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django/core/handlers/exception.py:39: in inner
    response = get_response(request)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django/core/handlers/base.py:249: in _legacy_get_response
    response = self._get_response(request)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django/core/handlers/base.py:187: in _get_response
    response = self.process_exception_by_middleware(e, request)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django/core/handlers/base.py:185: in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django/views/generic/base.py:68: in view
    return self.dispatch(request, *args, **kwargs)
src/oscar/apps/checkout/session.py:70: in dispatch
    request, *args, **kwargs)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django/views/generic/base.py:88: in dispatch
    return handler(request, *args, **kwargs)
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django/views/generic/edit.py:235: in get
    self.object = self.get_object()
../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django/views/generic/detail.py:32: in get_object
    queryset = self.get_queryset()
src/oscar/apps/checkout/views.py:207: in get_queryset
    return self.request.user.addresses.all()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x7f45db6627d0>>, args = ('addresses',)

    def inner(self, *args):
        if self._wrapped is empty:
            self._setup()
>       return func(self._wrapped, *args)
E       AttributeError: 'AnonymousUser' object has no attribute 'addresses'

../../.virtualenvs/oscar_tests/local/lib/python2.7/site-packages/django/utils/functional.py:235: AttributeError
```

However I don't know where to start to look for the initialization of self.request.user.
With all this subclassing and mixing, I'm a bit lost.
Perhaps you can point me to the right direction ?

Thanks

**Comment by CoffiDev** [comment]
Any news on this topic?

**Comment by pxg** [comment]
@CoffiDev I should have time to work on this in Q1 of 2017, but I have another project which needs to be finished first. The code appears to be stable, but we need to dig into why the tests are failing.

**Comment by rohit135** [comment]
hi guys!
I am new to django-oscar. Is there any solution for this issue or can you suggest any other django e-commerce framework?
thanks!

**Comment by pxg** [comment]
@rohit135 we have Django 1.10 compatibility in version 1.4 which will be officially released soon, we just need to fix a couple of tests, some of us are using the beta. The work for this is in the master branch if you'd like to help us test it.

**Comment by rohit135** [comment]
Thanks! Is there a release date scheduled? Also is there any issue with python3.6 and django1.9? I am thinking of using them for the moment..

**Comment by pxg** [comment]
There isn't an official release date, but I expect it will be released in the next couple of weeks. The test suite runs on Travis with Python 3.6 so this should be fine, Django 1.9 is fine too.
